In [14]:
import numpy as np

In [15]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [16]:
arr2 = np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


In [19]:
arr3 = np.linspace(0,1,5)
print(arr3)

[0.   0.25 0.5  0.75 1.  ]


In [20]:
arr4 = np.zeros(5)
print(arr4)

[0. 0. 0. 0. 0.]


In [22]:
arr5 = np.ones(5)
print(arr5)

[1. 1. 1. 1. 1.]


In [24]:
arr6 = np.full(5,7)
print(arr6)

[7 7 7 7 7]


In [26]:
arr7 = np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
arr8 = np.random.rand(5)
print(arr8)

[0.44670954 0.2981611  0.88684589 0.51818941 0.44780092]


In [43]:
arr9 = np.random.randint(1,10,size=5)
print(arr9)

[9 7 6 4 1]


In [45]:
arr_int = np.array([1, 2, 3])
arr_float= np.array([1.0, 2.0, 3.0])
arr_mixed = np.array([1, 2.5, 3])
# Mixed types + promoted to float
print(f"Integer: {arr_int.dtype}")
print(f"Float: {arr_float.dtype}")
print(f"Mixed: {arr_mixed.dtype} (promoted to float)\n")

Integer: int64
Float: float64
Mixed: float64 (promoted to float)



In [47]:
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}") # (rows, columns)
print(f"Dimensions: {matrix_2d.ndim}") # Number of dimensions
print(f"Size: {matrix_2d.size}") # Total number of elements
print(f"Data type: {matrix_2d.dtype}") # Data type of elements

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64


In [53]:
# 2D array (matrix)
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array (Matrix):")
print(matrix_2d)
print(f"Shape: {matrix_2d.shape}") # (rows, columns)
print(f"Dimensions: {matrix_2d.ndim}") # Number of dimensions
print(f"Size: {matrix_2d.size}") # Total number of elements
print(f"Data type: {matrix_2d.dtype}") # Data type of elements

# 3D array
matrix_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:")
print(matrix_3d)
print(f"Shape: {matrix_3d.shape}") # (depth, rows, columns)

# Creating multi-dimensional arrays with specific shapes
zeros_2d = np.zeros((3, 4)) # 3 rows, 4 columns
print("\n2D zeros array:")
print(zeros_2d)

ones_3d = np.ones((2,3,4)) # 2x3x4 array
print(ones_3d)
print(f"\n3D ones array shape: {ones_3d. shape}")

2D Array (Matrix):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int64

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)

2D zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

3D ones array shape: (2, 3, 4)


In [55]:
arr = np.array([[1,2,],[3,4],[5,6]])
sum = np.sum(arr, axis=1)
print(sum)

[ 3  7 11]
